export interface TableDef {
  name: string
  rows: number | null
  fields: string[]
}

export interface Layer {
  id: number
  name: string
  description: string
  detail: string
  whyItMatters: string
  tables: TableDef[]
  color: string
  dot: string
  accent: string
  border: string
}

export const LAYERS: Layer[] = [
  {
    id: 1,
    name: 'Source Layer',
    description: 'Raw files — ECB / BIS / BISTA',
    detail: 'Four external data sets ingested as-is: ECB Supervisory Banking Statistics (Excel), BIS statistics (CSV), BISTA bank-level data (CSV), ECB Eurosystem balance sheet (XML/CSV). Generated by regulators and loaded without modification.',
    whyItMatters: 'This is the ground truth. If a regulator ever questions a figure, we can trace it back to the exact raw file and line number. Nothing is altered at this stage — ever.',
    tables: [
      { name: 'data/raw/ecb_sup/ (Excel)', rows: 855, fields: ['REF_AREA', 'INSTRUMENT', 'DATA_TYPE', 'OBS_VALUE', 'TIME_PERIOD'] },
      { name: 'data/raw/bista/ (CSV)', rows: 1029756, fields: ['bank_id', 'report_date', 'item_code', 'value', 'currency'] },
      { name: 'data/raw/eba/ (CSV/XML)', rows: 4101, fields: ['reporting_entity', 'template', 'row', 'col', 'value'] },
      { name: 'data/raw/ecb_sup/ (Eurosystem)', rows: 1134, fields: ['date', 'asset_class', 'counterparty', 'amount_eur'] },
    ],
    color: 'bg-slate-50 text-slate-700',
    dot: 'bg-slate-400',
    accent: 'text-slate-600',
    border: 'border-slate-300',
  },
  {
    id: 2,
    name: 'Staging Layer',
    description: 'PostgreSQL — schema: staging',
    detail: 'Raw data loaded verbatim into typed PostgreSQL tables. No transformations — only type coercion (string → numeric). Each row carries a load_timestamp and source_file path for full provenance.',
    whyItMatters: 'Regulators such as the ECB or national competent authorities can request an audit at any time. The staging layer is our immutable ledger — retained for 7 years. If the warehouse ever needs to be rebuilt, staging is the source of truth.',
    tables: [
      { name: 'staging.ecb_supervisory_raw', rows: 855, fields: ['id', 'ref_area', 'instrument', 'obs_value', 'time_period', 'load_ts', 'source_file'] },
      { name: 'staging.bista_raw', rows: 1029756, fields: ['id', 'bank_id', 'report_date', 'item_code', 'value', 'load_ts'] },
      { name: 'staging.eba_raw', rows: 4101, fields: ['id', 'entity', 'template', 'row_key', 'col_key', 'value', 'load_ts'] },
      { name: 'staging.ecb_eurosystem_raw', rows: 1134, fields: ['id', 'date', 'asset_class', 'amount_eur', 'load_ts'] },
    ],
    color: 'bg-blue-50 text-blue-700',
    dot: 'bg-blue-400',
    accent: 'text-blue-600',
    border: 'border-blue-200',
  },
  {
    id: 3,
    name: 'Warehouse Layer',
    description: 'PostgreSQL — schema: warehouse',
    detail: 'Basel III mapping rules applied in Python (services/transform.py). HQLA assets classified by liquidity tier and haircut applied. Net outflows computed using regulatory run-off rates. LCR = HQLA ÷ Net 30-day Outflow. NSFR = ASF ÷ RSF.',
    whyItMatters: 'This is where raw ECB index numbers become regulatory ratios. Every formula here is traceable to CRR Article 412 (LCR) and Article 428 (NSFR). Auditors can review the SQL views to verify the mapping is correct.',
    tables: [
      { name: 'warehouse.bank_lcr', rows: 38, fields: ['bank_id', 'reference_date', 'hqla_amount', 'net_outflow', 'lcr_ratio', 'computed_at'] },
      { name: 'warehouse.bank_nsfr', rows: 19, fields: ['bank_id', 'reference_date', 'asf_amount', 'rsf_amount', 'nsfr_ratio', 'computed_at'] },
      { name: 'warehouse.supervisory_series', rows: 855, fields: ['series_key', 'ref_area', 'instrument', 'obs_value', 'time_period'] },
    ],
    color: 'bg-indigo-50 text-indigo-700',
    dot: 'bg-indigo-400',
    accent: 'text-indigo-600',
    border: 'border-indigo-200',
  },
  {
    id: 4,
    name: 'Validation Layer',
    description: 'PostgreSQL — schema: validation',
    detail: 'Business rules execute after each warehouse load. Examples: LCR must be positive, HQLA must exceed outflows when LCR > 100%, NSFR ASF must be positive. Failures are written to validation.rule_results with a severity level and blocked from reaching the API.',
    whyItMatters: 'This layer stops bad data from reaching risk managers and regulators. A silent error in a Basel III report can result in a capital misstatement. Every failure is timestamped and logged — not silently discarded.',
    tables: [
      { name: 'validation.rule_results', rows: null, fields: ['id', 'run_id', 'rule_name', 'severity', 'row_ref', 'message', 'checked_at'] },
      { name: 'validation.pipeline_runs', rows: null, fields: ['id', 'started_at', 'finished_at', 'status', 'trigger'] },
    ],
    color: 'bg-amber-50 text-amber-700',
    dot: 'bg-amber-400',
    accent: 'text-amber-600',
    border: 'border-amber-200',
  },
  {
    id: 5,
    name: 'Reporting Layer',
    description: 'FastAPI REST API + React Dashboard',
    detail: 'FastAPI reads from warehouse views and serves typed JSON to the React dashboard. Data is available for LCR, NSFR, data quality, and lineage. Audience: Risk Managers, CFO, Regulators.',
    whyItMatters: 'The dashboard is the final mile — where data becomes decisions. LCR and NSFR breaches trigger alerts that can result in capital raises, asset disposals, or regulatory notification within 24 hours under CRD IV Article 414.',
    tables: [
      { name: 'Summary endpoint', rows: null, fields: ['lcr_ratio', 'nsfr_ratio', 'data_quality_score', 'lcr_trend[]', 'active_alerts[]'] },
      { name: 'LCR metrics endpoint', rows: null, fields: ['banks[].bank_id', 'banks[].lcr_ratio', 'banks[].hqla_amount', 'avg_lcr', 'min_lcr'] },
      { name: 'NSFR metrics endpoint', rows: null, fields: ['banks[].nsfr_ratio', 'banks[].asf_amount', 'banks[].rsf_amount', 'avg_nsfr'] },
    ],
    color: 'bg-emerald-50 text-emerald-700',
    dot: 'bg-emerald-400',
    accent: 'text-emerald-600',
    border: 'border-emerald-200',
  },
]

export type Metric = 'LCR ratio' | 'NSFR ratio'

export const QUARTERS = [
  '2025 Q4', '2025 Q3', '2025 Q2', '2025 Q1',
  '2024 Q4', '2024 Q3', '2024 Q2', '2024 Q1',
]

export interface TraceStep {
  layer: string
  color: string
  icon: string
  detail: string
}

export function buildTrace(metric: Metric, quarter: string): TraceStep[] {
  const isLcr = metric === 'LCR ratio'
  const [year, q] = quarter.split(' ')
  const month = ({ Q1: '03', Q2: '06', Q3: '09', Q4: '12' } as Record<string, string>)[q] ?? '12'
  const refDate = `${year}-${month}-31`
  const qNoSpace = quarter.replace(' ', '')

  return [
    {
      layer: 'Source Data Extraction',
      color: 'border-slate-200',
      icon: 'SRC',
      detail: isLcr
        ? `LCR ratio for the selected quarter retrieved from ECB Supervisory Banking Statistics, covering Significant Institutions under the Single Supervisory Mechanism.`
        : `NSFR ratio for the selected quarter retrieved from ECB Supervisory Banking Statistics, covering Significant Institutions under the Single Supervisory Mechanism.`
    },
    {
      layer: 'Raw Data Archive',
      color: 'border-slate-200',
      icon: 'STG',
      detail: `Source data stored without modification. Every record is timestamped and retained for 7 years to satisfy regulatory audit requirements.`,
    },
    {
      layer: 'Regulatory Transformation',
      color: 'border-slate-200',
      icon: 'WH',
      detail: `Raw figures converted into LCR components: HQLA buffer and net cash outflows, applying Basel III run-off rates as required under CRR Article 416/422.`,
    },
    {
      layer: 'Data Service Layer',
      color: 'border-slate-200',
      icon: 'API',
      detail: `Validated metrics made available to the dashboard through a structured data service. Only warehouse-approved figures are served.`,
    },
    {
      layer: 'Dashboard Display',
      color: 'border-slate-200',
      icon: 'UI',
      detail: `Final validated figure displayed on the Executive Terminal. The Stress Test Simulator can apply a funding shock to model a hypothetical scenario — the underlying warehouse record remains unchanged.`,
    },
  ]
}

export function getHighlightTable(layerId: number, metric: Metric | null): string | undefined {
  if (!metric) return undefined
  const isLcr = metric === 'LCR ratio'
  switch (layerId) {
    case 1: return 'data/raw/ecb_sup/ (Excel)'
    case 2: return 'staging.ecb_supervisory_raw'
    case 3: return isLcr ? 'warehouse.bank_lcr' : 'warehouse.bank_nsfr'
    case 4: return 'validation.rule_results'
    case 5: return isLcr ? 'LCR metrics endpoint' : 'NSFR metrics endpoint'
  }
}
